parallel-jobs = 1
logging-to-file = true      
enable-magisk-update = false

[Youtube-Amoled]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode="apk"
apkmirror-arch = "arm64-v8a"
included-patches = "materialyou"
excluded-patches = "custom-branding-youtube-name custom-branding-icon-revancify-blue custom-branding-icon-revancify-red custom-branding-icon-mmt"

[YT-Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-arch = "arm64-v8a"
excluded-patches = "custom-branding-music-name custom-branding-icon-revancify-blue custom-branding-icon-revancify-red custom-branding-icon-mmt"
