enable-magisk-update = false

[Youtube-Amoled]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "auto"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode="apk"
arch = "arm64-v8a"
included-patches = "'MaterialYou'"
excluded-patches = "'Custom branding name YouTube' 'Custom branding icon YouTube'"

[YT-Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
version = "auto"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "arm64-v8a"
excluded-patches = "'Custom branding name YouTube Music' 'Custom branding icon YouTube Music'"
