name: GitHub Cleanup

on:
  workflow_dispatch:
    inputs:
      CLEANUP:
        description: 'Clear GitHub'
        required: false
        type: boolean
        default: true

jobs:
  cleanup:
    name: GitHub Cleanup
    if: ${{ inputs.CLEANUP }}
    uses: dev-drprasad/delete-older-releases@v0.2
  with:
    repo: <owner>/<repoName> # defaults to current repo
    keep_latest: 3
    delete_tag_pattern: beta # defaults to ""
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
